version: "3.8"

services:
  backend:
    build:
      context: ./backend
    ports:
      - "5000:5000"
    volumes:
      - ./backend/static/audio:/app/static/audio
    environment:
      FLASK_ENV: production

  frontend:
    build:
      context: ./frontend
    ports:
      - "80:80"
    environment:
      VITE_BACKEND_URL: http://localhost:5000